In [352]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report, precision_score, recall_score, accuracy_score, f1_score
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import cohen_kappa_score
from sklearn.tree import DecisionTreeClassifier


In [353]:
data=pd.read_csv('/kaggle/input/blooddonation/transfusion.csv')
data.head(3)

Recency (months)  Frequency (times)  Monetary (c.c. blood)  Time (months)  \
0                 2                 50                  12500             98   
1                 0                 13                   3250             28   
2                 1                 16                   4000             35   

   whether he/she donated blood in March 2007  
0                                           1  
1                                           1  
2                                           1

In [354]:
data.isnull().sum()

Recency (months)                              0
Frequency (times)                             0
Monetary (c.c. blood)                         0
Time (months)                                 0
whether he/she donated blood in March 2007    0
dtype: int64

In [355]:
X=data[['Recency (months)', 'Frequency (times)', 'Monetary (c.c. blood)','Time (months)']]
y=data['whether he/she donated blood in March 2007']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)


In [356]:
X_train.shape

(523, 4)

In [357]:
X_test.shape

(225, 4)

In [358]:
y_train.shape

(523,)

In [359]:
classifier= RandomForestClassifier(n_estimators= 10)  
classifier.fit(X_train, y_train) 

RandomForestClassifier(n_estimators=10)

In [360]:
y_pred= classifier.predict(X_test)

In [361]:
def eval_metrics(model, X_train, y_train, X_test, y_test):
    y_train_pred = model.predict(X_train)
    y_pred = model.predict(X_test)
    
    print("Test_Set")
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print()
    print("Train_Set")
    print(confusion_matrix(y_train, y_train_pred))
    print(classification_report(y_train, y_train_pred))

In [362]:
eval_metrics(classifier,X_train, y_train, X_test, y_test)

Test_Set
[[153  18]
 [ 34  20]]
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       171
           1       0.53      0.37      0.43        54

    accuracy                           0.77       225
   macro avg       0.67      0.63      0.64       225
weighted avg       0.75      0.77      0.75       225


Train_Set
[[392   7]
 [ 34  90]]
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       399
           1       0.93      0.73      0.81       124

    accuracy                           0.92       523
   macro avg       0.92      0.85      0.88       523
weighted avg       0.92      0.92      0.92       523



In [363]:
from xgboost import XGBClassifier
xgb_model=XGBClassifier()
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [364]:
eval_metrics(xgb_model,X_train, y_train, X_test, y_test)

Test_Set
[[148  23]
 [ 36  18]]
              precision    recall  f1-score   support

           0       0.80      0.87      0.83       171
           1       0.44      0.33      0.38        54

    accuracy                           0.74       225
   macro avg       0.62      0.60      0.61       225
weighted avg       0.72      0.74      0.72       225


Train_Set
[[393   6]
 [ 31  93]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96       399
           1       0.94      0.75      0.83       124

    accuracy                           0.93       523
   macro avg       0.93      0.87      0.89       523
weighted avg       0.93      0.93      0.93       523



In [365]:
model =  DecisionTreeClassifier( max_depth=10)

In [366]:
 model.fit(X_train, y_train)
 y_train_pred = model.predict(X_train)
 y_pred = model.predict(X_test)
 train_acc= accuracy_score(y_train, y_train_pred)
 test_acc= accuracy_score(y_test, y_pred)
    

In [367]:
train_acc

0.9063097514340345

In [368]:
test_acc

0.7155555555555555

In [369]:
import pickle
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))